apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: skaffold-demo
build:
  artifacts:
    - image: skaffold-buildpacks-node
      buildpacks:
        builder: gcr.io/buildpacks/builder:v1
manifests:
  rawYaml:
    - k8s/web.yaml
